project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - slides.qmd
    - live_sessions.qmd
  resources:
    - slides/*.html
    - CNAME
    - .nojekyll
        
website:
  title: ""
  search: false

  navbar:
    search: false  
    link-external-newwindow: true
    title: BUSI 721
    file: index.qmd
    right:

      - text: Notebook Repo
        href: https://github.com/kerryback/2023-721-901-binder

      - text: Slide Decks
        file: slides.qmd

      - text: Live Session Recordings
        file: live_sessions.qmd

      - text: Solutions 
        href: https://github.com/kerryback/busi721-901/tree/main/solutions


      - text: Learn Investments
        href: https://learn-investments.rice-business.org

      
format:
  html:
    theme:
      light: flatly
      dark: superhero
    link-external-newwindow: true
    



